// teambuild — collaborative teams.
//
//   POST   /api/teams                       create a team (you become owner + member)
//   GET    /api/teams                       teams you own or belong to
//   GET    /api/teams/:tid                  team info (name, members, invite code)
//   POST   /api/teams/:tid/join             { invite_code } — join a team
//   POST   /api/teams/:tid/leave            leave a team
//   DELETE /api/teams/:tid                  owner deletes a team
//   POST   /api/projects/:pid/team          { team_id } — attach/detach a team to a project
//
// A project attached to a team can be edited + generated by every team member
// (canWrite in auth.js), their chats spend from the team's shared credit pool,
// and every member sees the others' live presence cursors in the builder.

import { Hono } from 'hono';
import { store } from './store.js';
import { requireUser } from './auth.js';

export const teams = new Hono();

const TEAM_NAME_RE = /^[A-Za-z0-9 _\-]{2,40}$/;

function cleanName(raw) {
  return String(raw || '').trim().slice(0, 40);
}

teams.post('/api/teams', requireUser, async (c) => {
  const name = cleanName((await c.req.json().catch(() => ({}))).name);
  if (!TEAM_NAME_RE.test(name)) return c.json({ error: 'team name: 2-40 letters, digits, spaces, - or _' }, 400);
  const team = await store.createTeam(name, c.get('user').name);
  return c.json({ team }, 201);
});

teams.get('/api/teams', requireUser, async (c) => {
  return c.json(await store.myTeams(c.get('user').name));
});

// Look up a team by its invite code (lets a member paste just the code to join).
teams.get('/api/teams/by-invite/:code', requireUser, async (c) => {
  const code = String(c.req.param('code') || '').trim().toUpperCase();
  if (!code || code.length < 4) return c.json({ error: 'enter the invite code' }, 400);
  const t = await store.teamByInviteCode(code);
  if (!t) return c.json({ error: 'no team found for that invite code' }, 404);
  return c.json({ id: t.id, name: t.name, owner: t.owner, members: Number(t.members || t.member_count || 0) });
});

teams.get('/api/teams/:tid', requireUser, async (c) => {
  const tid = c.req.param('tid');
  const me = c.get('user').name;
  const t = await store.teamInfo(tid);
  if (!t) return c.json({ error: 'team not found' }, 404);
  const mine = t.owner === me || t.members.includes(me);
  if (!mine) return c.json({ error: "you're not a member of this team" }, 403);
  return c.json(t);
});

teams.post('/api/teams/:tid/join', requireUser, async (c) => {
  const tid = c.req.param('tid');
  const { invite_code } = await c.req.json().catch(() => ({}));
  const t = await store.teamInfo(tid);
  if (!t) return c.json({ error: 'team not found' }, 404);
  const code = String(invite_code || '').trim().toUpperCase();
  if (!code || code !== t.invite_code) return c.json({ error: 'invalid invite code' }, 403);
  const me = c.get('user').name;
  if (t.members.includes(me)) return c.json({ error: 'you are already a member' }, 409);
  await store.addTeamMember(tid, me);
  return c.json(await store.teamInfo(tid), 201);
});

teams.post('/api/teams/:tid/leave', requireUser, async (c) => {
  const tid = c.req.param('tid');
  const me = c.get('user').name;
  const t = await store.teamInfo(tid);
  if (!t) return c.json({ error: 'team not found' }, 404);
  if (!t.members.includes(me)) return c.json({ error: "you're not a member" }, 403);
  await store.removeTeamMember(tid, me);
  return c.json({ ok: true });
});

teams.delete('/api/teams/:tid', requireUser, async (c) => {
  const tid = c.req.param('tid');
  const t = await store.teamInfo(tid);
  if (!t) return c.json({ error: 'team not found' }, 404);
  if (t.owner !== c.get('user').name) return c.json({ error: 'only the team owner can delete it' }, 403);
  await store.deleteTeam(tid);
  return c.json({ ok: true });
});

// Share a project with a team (owner only). team_id '' detaches it.
teams.post('/api/projects/:pid/team', requireUser, async (c) => {
  const pid = c.req.param('pid');
  const project = await store.getProject(pid);
  if (!project) return c.json({ error: 'not found' }, 404);
  if (project.owner && project.owner !== c.get('user').name) {
    return c.json({ error: "you don't own this project" }, 403);
  }
  const { team_id } = await c.req.json().catch(() => ({}));
  const tid = String(team_id || '').trim();
  if (tid) {
    const t = await store.teamInfo(tid);
    if (!t) return c.json({ error: 'team not found' }, 404);
    if (!(await store.isTeamMember(tid, c.get('user').name))) {
      return c.json({ error: 'join the team before sharing a project with it' }, 403);
    }
  }
  return c.json(await store.setProjectTeam(pid, tid));
});