-- ============================================================================
-- API v1 storage migration: identical surface to the Cloudflare D1 store,
-- implemented on Supabase Postgres (service_role is the only writer).
--
-- Storage model notes:
--   * BaaS collections — D1 lazily created `baas_<proj>_<coll>` tables; Postgres
--     cannot runtime-DDL through PostgREST, so every collection collapses into
--     one a1_baas (JSONB) table keyed (pid, coll, row_id).
--   * events.seq is a global identity column (same semantic as D1 AUTOINCREMENT),
--     so distinct rooms share one sequence.
--   * Atomic counters (usage/earnings) go through the a1_incr_rate / a1_earn /
--     a1_spend functions so concurrent requests never lose increments.
--   * Every table is RLS-enabled with no policies: only the service_role key
--     can read/write. anon/authenticated get nothing (matches the v2 lockdown).
-- ============================================================================

begin;

-- ---- projects --------------------------------------------------------------
create table if not exists public.projects (
  id          text primary key,
  name        text not null,
  created_at  bigint not null,
  model       text,
  published   integer not null default 0,
  slug        text,
  description text not null default '',
  owner       text not null default '',
  plan        text,
  team_id     text not null default ''
);

-- ---- files -----------------------------------------------------------------
create table if not exists public.files (
  project_id text not null references public.projects(id) on delete cascade,
  path       text not null,
  content    text not null,
  encoding   text not null default 'utf8',
  updated_at bigint not null,
  primary key (project_id, path)
);
create index if not exists idx_files_project on public.files (project_id);

-- ---- messages --------------------------------------------------------------
create table if not exists public.messages (
  project_id text not null references public.projects(id) on delete cascade,
  role       text not null,
  content    text not null,
  "user"     text not null default '',
  created_at bigint not null
);
create index if not exists idx_messages_project on public.messages (project_id, created_at);

-- ---- users & sessions ------------------------------------------------------
create table if not exists public.users (
  id         text primary key,
  name       text unique not null,
  phash      text not null,
  email      text not null default '',
  verified   integer not null default 0,
  created_at bigint not null,
  ip         text not null default ''
);

create table if not exists public.sessions (
  token   text primary key,
  user_id text not null references public.users(id) on delete cascade,
  exp     bigint not null
);
create index if not exists idx_sessions_user on public.sessions (user_id);

-- ---- usage (daily counters: api limiter, daily credits, team pools) --------
create table if not exists public.a1_usage (
  name  text not null,
  day   text not null,
  count integer not null default 0,
  primary key (name, day)
);

create or replace function public.a1_incr_rate(_name text, _day text, _amount int)
returns int language sql volatile as $$
  insert into public.a1_usage (name, day, count) values (_name, _day, _amount)
  on conflict (name, day) do update set count = public.a1_usage.count + excluded.count
  returning count;
$$;

-- ---- meta ------------------------------------------------------------------
create table if not exists public.meta (
  k text primary key,
  v text not null
);

-- ---- multiplayer / chat event log ------------------------------------------
create table if not exists public.events (
  seq  bigint generated by default as identity primary key,
  pid  text not null,
  room text not null,
  data text not null
);
create index if not exists idx_events_room on public.events (pid, room, seq);

-- ---- per-file revision history ---------------------------------------------
create table if not exists public.file_versions (
  project_id text not null references public.projects(id) on delete cascade,
  path       text not null,
  seq        integer not null,
  content    text,
  encoding   text not null default 'utf8',
  updated_at bigint not null,
  primary key (project_id, path, seq)
);
create index if not exists idx_file_versions on public.file_versions (project_id, path, seq);

-- ---- project snapshots -----------------------------------------------------
create table if not exists public.snapshots (
  id         text primary key,
  project_id text not null references public.projects(id) on delete cascade,
  created_at bigint not null,
  label      text not null default ''
);
create index if not exists idx_snapshots_project on public.snapshots (project_id, created_at);

create table if not exists public.snapshot_files (
  snapshot_id text not null references public.snapshots(id) on delete cascade,
  path        text not null,
  content     text not null,
  encoding    text not null default 'utf8',
  primary key (snapshot_id, path)
);

-- ---- teams ----------------------------------------------------------------
create table if not exists public.teams (
  id          text primary key,
  name        text not null,
  owner       text not null,
  invite_code text unique not null,
  created_at  bigint not null
);

create table if not exists public.team_members (
  team_id   text not null,
  name      text not null,
  joined_at bigint not null,
  primary key (team_id, name)
);
create index if not exists idx_team_members on public.team_members (team_id);

-- ---- credit exchange -------------------------------------------------------
create table if not exists public.interactions (
  project_id text not null references public.projects(id) on delete cascade,
  day        text not null,
  key        text not null,
  created_at bigint not null,
  primary key (project_id, day, key)
);

create table if not exists public.earnings (
  name  text primary key,
  units integer not null default 0
);

create or replace function public.a1_earn(_name text, _units int)
returns int language sql volatile as $$
  insert into public.earnings (name, units) values (_name, _units)
  on conflict (name) do update set units = public.earnings.units + excluded.units
  returning units;
$$;

create or replace function public.a1_spend(_name text, _units int)
returns int language sql volatile as $$
  update public.earnings set units = greatest(0, units - _units) where name = _name
  returning units;
$$;

-- ---- live presence ---------------------------------------------------------
create table if not exists public.presence (
  pid     text not null references public.projects(id) on delete cascade,
  sid     text not null,
  "user"  text not null default '',
  seen_at bigint not null,
  primary key (pid, sid)
);

-- ---- BaaS (serialized JSON collections, one table for all projects) -------
create table if not exists public.a1_baas (
  pid        text not null references public.projects(id) on delete cascade,
  coll       text not null,
  row_id     text not null,
  data       jsonb not null default '{}'::jsonb,
  created_at bigint not null,
  primary key (pid, coll, row_id)
);
create index if not exists idx_a1_baas_coll on public.a1_baas (pid, coll, created_at);

-- ---- community feature voting ---------------------------------------------
create table if not exists public.features (
  id          text primary key,
  title       text not null,
  description text not null default '',
  status      text not null default 'proposed',
  created_by  text not null default '',
  created_at  bigint not null
);

create table if not exists public.feature_votes (
  feature_id text not null references public.features(id) on delete cascade,
  "user"     text not null,
  vote       integer not null,
  updated_at bigint not null,
  primary key (feature_id, "user")
);
create index if not exists idx_feature_votes on public.feature_votes (feature_id);

-- ---- lock everything down --------------------------------------------------
-- RLS on with zero policies = service_role-only access (bypasses RLS); nothing
-- is exposed to anon/authenticated. Mirrors the ~/v2 lockdown philosophy.
do $$
declare t record;
begin
  for t in select tablename from pg_tables
           where schemaname = 'public' and tablename in (
             'projects','files','messages','users','sessions','a1_usage','meta',
             'events','file_versions','snapshots','snapshot_files','teams',
             'team_members','interactions','earnings','presence','a1_baas',
             'features','feature_votes')
  loop
    execute format('alter table public.%I enable row level security', t.tablename);
  end loop;
end $$;

commit;