#!/usr/bin/env bash
# One-time setup for the KAGGLE remote executor (aibuilder relay agent).
#
# NOTE (2026-09): on this account, Kaggle notebook kernels have NO outbound
# internet at all (UI runs return HTTP 000; raw TCP to public IPs times out;
# there is no "Internet" toggle in the UI). agent.py therefore cannot reach the
# relay from inside a Kaggle kernel on this account. Use it on any OTHER
# internet-connected host instead:
#
#   KTERM_TOKEN=<we> RELAY_URL=https://aibuilderapi.csomeone301.workers.dev \
#     KTERM_ROOT=/srv/aibuilder-sandbox nohup python3 agent.py >> /tmp/aib-agent.log 2>&1 &
#
# The relay is enabled whenever the worker's KAGGLE_RELAY_URL var is set, and
# /api/kterm/status -> agentsOnline shows whether an agent is currently polling
# (last seen within 120s).
#
# Run on the DEVICE (where your Kaggle API token lives) to store the token and
# print the steps to start the agent on a remote host:
#
#   KAGGLE_API_TOKEN=KGAT_... bash kaggeld/setup.sh
#
# The token is written ONLY to ~/.kaggle/access_token (chmod 600) and is NEVER
# committed to the repo. It is used with Bearer auth on Kaggle's API (only needed
# if you push/start notebooks programmatically from this device).
#
# NOTE: the Kaggle API token must NEVER be put inside the notebook. The agent in
# the notebook authenticates against the relay, which is locked with the worker's
# TERMINAL_TOKEN (the 64-char value generated by the builder's terminal setup,
# NOT the Kaggle API key). KTERM_TOKEN below == TERMINAL_TOKEN.
#
# After running, do the ONE-TIME notebook setup:
#   1. Create a Notebook on https://www.kaggle.com (Python, any dataset or none)
#      -> Settings -> Secrets -> add two notebook secrets:
#           KTERM_TOKEN = <TERMINAL_TOKEN of the aibuilder worker>
#           RELAY_URL   = https://aibuilderapi.csomeone301.workers.dev
#   2. Internet must be enabled (Settings -> Internet -> On).
#   3. In a code cell, run:
#         %%bash
#         git clone --depth 1 https://github.com/wigmastrrrrrrrrjr/aibuilder /tmp/aib
#         cat > /tmp/run_agent.sh <<'EOF'
#         set -e
#         pip install -q requests
#         KTERM_TOKEN="$(python3 - <<'PY'
# from kaggle_secrets import UserSecretsClient
# print(UserSecretsClient().get_secret("KTERM_TOKEN"))
# PY
#         )" RELAY_URL="$(python3 - <<'PY'
# from kaggle_secrets import UserSecretsClient
# print(UserSecretsClient().get_secret("RELAY_URL"))
# PY
#         )" nohup python3 /tmp/aib/aibuilderapi/terminald/kaggeld/agent.py >> /tmp/agent.log 2>&1 &
#         EOF
#         bash /tmp/run_agent.sh
#         sleep 4 && tail -5 /tmp/agent.log
#   Each notebook session has a time budget; keep a window open or schedule
#   recurrences. The builder falls back to the normal terminal when the agent is
#   idle (status check: https://aibuilderapi.csomeone301.workers.dev/api/kterm/status).

set -euo pipefail

[ -n "${KAGGLE_API_TOKEN:-}" ] || { echo "KAGGLE_API_TOKEN is required" >&2; exit 1; }

mkdir -p "$HOME/.kaggle"
umask 177
printf '%s' "$KAGGLE_API_TOKEN" > "$HOME/.kaggle/access_token"
chmod 600 "$HOME/.kaggle/access_token"

echo "token written to $HOME/.kaggle/access_token (chmod 600)"
echo "hex digest: $(printf '%s' "$KAGGLE_API_TOKEN" | sha256sum | cut -c1-16)"
echo
echo "Notebook setup: readonly the steps above. Add secrets KTERM_TOKEN and RELAY_URL,
enable Internet, and run the %%bash cell. agent.py polls /api/kterm for jobs."
echo "Health: curl https://aibuilderapi.csomeone301.workers.dev/api/kterm/status"